# Generated by Django 4.1 on 2022-08-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_customer_alter_employee_options_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rating',
        ),
    ]
