# Generated by Django 4.1 on 2022-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_employee_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='time_slot',
            field=models.JSONField(default=''),
        ),
    ]
