# Generated by Django 4.1 on 2022-08-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
